# Xamarin.Android

# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

jobs:
  - job: Android
    pool:
      vmImage: 'macos-latest'

    variables:
      buildConfiguration: 'Release'
      outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: XamarinAndroid@1
      inputs:
        projectFile: '**/*droid*.csproj'
        outputDirectory: '$(outputDirectory)'
        configuration: '$(buildConfiguration)'
        
    - task: AndroidSigning@3
      inputs:
        apkFiles: '$(outputDirectory)/**/*.apk'
        apksignerKeystoreFile: 'key.keystore'
        apksignerKeystorePassword: '$(keystore-pass)'
        apksignerKeystoreAlias: 'key'
        apksignerKeyPassword: '$(key-pass)'

  - job: iOS
    pool:
      vmImage: 'macos-latest'
    steps:
    - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
      displayName: 'Select the Xamarin SDK version'
      enabled: false
      
    - task: NuGetToolInstaller@1
    
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: XamariniOS@2
      inputs:
        solutionFile: '**/*.sln'
        configuration: 'Release'
        buildForSimulator: true
        packageApp: false
